3.2.3-2: Lintian fixes.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -33,7 +33,7 @@ dpkg-statoverride --list /usr/bin/jwhois > /dev/null || jwhoisoverride=0
 
 if test "$jwhoisoverride" = "0"; then
   if getent group jwhois > /dev/null; then
-    if chown root.jwhois /usr/bin/jwhois; then
+    if chown root:jwhois /usr/bin/jwhois; then
       chmod 02755 /usr/bin/jwhois || echo "Failed setting jwhois permissions, cache functionality may be impaired."
     else
       echo "Failed setting jwhois ownership, cache functionality may be impaired."
@@ -50,7 +50,7 @@ dpkg-statoverride --list /var/cache/jwhois > /dev/null || cacheoverride=0
 
 if test "$cacheoverride" = "0"; then
   if getent group jwhois > /dev/null; then
-    if chown root.jwhois /var/cache/jwhois; then
+    if chown root:jwhois /var/cache/jwhois; then
       chmod 0775 /var/cache/jwhois || echo "Failed setting cache directory permissions, cache functionality may be impaired."
     else
       echo "Failed setting cache directory ownership, cache functionality may be impaired."
@@ -61,12 +61,12 @@ if test "$cacheoverride" = "0"; then
     # by root (bug#95013).
 
     if test -e /var/cache/jwhois/jwhois.db; then
-      chown root.jwhois /var/cache/jwhois/jwhois.db || echo "Failed setting cache file ownership, cache functionality may be impaired."
+      chown root:jwhois /var/cache/jwhois/jwhois.db || echo "Failed setting cache file ownership, cache functionality may be impaired."
       chmod 0660 /var/cache/jwhois/jwhois.db || echo "Failed setting cache permissions, cache functionality may be impaired."
     else
       if touch /var/cache/jwhois/jwhois.db; then
         if test -f /var/cache/jwhois/jwhois.db; then
-          chown root.jwhois /var/cache/jwhois/jwhois.db || echo "Failed setting cache file ownership, cache functionality may be impaired."
+          chown root:jwhois /var/cache/jwhois/jwhois.db || echo "Failed setting cache file ownership, cache functionality may be impaired."
           chmod 0660 /var/cache/jwhois/jwhois.db || echo "Failed setting cache permissions, cache functionality may be impaired."
         else
           echo "Cache file is not a regular file, cache functionality may be impaired."
