Fix statoverride crap

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -21,39 +21,31 @@ fi
 
 addgroup --system jwhois || true
 
-# Check if we have current overrides for the binary and cache
+# Setgid binary to the jwhois group if no statoverride was set
 
 jwhoisoverride=`dpkg-statoverride --list /usr/bin/jwhois`
-cacheoverride=`dpkg-statoverride --list /var/cache/jwhois`
-
-# Setgid binary to the jwhois group, and add it to dpkg-statoverride
-# unless it's already overriden.
-
-if chown root.jwhois /usr/bin/jwhois; then
-  chmod 02755 /usr/bin/jwhois
-fi
-
 if test "$jwhoisoverride" = ""; then
-  dpkg-statoverride --add root jwhois 02755 /usr/bin/jwhois || echo "Failed adding statoverride for /usr/bin/jwhois"
-else
-  echo Statoverride already set for /usr/bin/jwhois
+  if chown root.jwhois /usr/bin/jwhois; then
+    chmod 02755 /usr/bin/jwhois || echo "Failed setting jwhois permissions, cache functionality may be impaired."
+  else
+    echo "Failed setting jwhois ownership, cache functionality may be impaired."
+  fi
 fi
 
 # Setgid cache directory to the jwhois group, and add it to
 # dpkg-statoverride unless it's already overridden.
 
-if chown root.jwhois /var/cache/jwhois; then
-  chmod 0775 /var/cache/jwhois
-fi
-
+cacheoverride=`dpkg-statoverride --list /var/cache/jwhois`
 if test "$cacheoverride" = ""; then
-  dpkg-statoverride --add root jwhois 0775 /var/cache/jwhois || echo "Failed adding statoverride for /var/cache/jwhois"
-else
-  echo Statoverride already set for /var/cache/jwhois
-fi
+  if chown root.jwhois /var/cache/jwhois; then
+    chmod 0775 /var/cache/jwhois || echo "Failed setting cache directory permissions, cache functionality may be impaired."
+  else
+    echo "Failed setting cache directory ownership, cache functionality may be impaired."
+  fi
 
-# Make sure the cache, if it exists, has the correct group ownership
+  # Make sure the cache, if it exists, has the correct group ownership
 
-if test -e /var/cache/jwhois/jwhois.db; then
-  chgrp jwhois /var/cache/jwhois/jwhois.db || echo "Failed setting ownership on cache file - cache functions will not work."
+  if test -e /var/cache/jwhois/jwhois.db; then
+    chgrp jwhois /var/cache/jwhois/jwhois.db || echo "Failed setting cache file ownership, cache functionality may be impaired."
+  fi
 fi
