Use dpkg 1.9.0 check to see if statoverride is set.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -19,18 +19,19 @@ fi
 
 # Add the group 'jwhois' that the cache uses
 
-if getent group jwhois > /dev/null; then
-  # Group already exists
-  true
-else
+groupexist=1
+getent group jwhois > /dev/null || groupexist=0
+if test "$groupexist" = "0" then
   # Group did not exist
-  addgroup --system jwhois || true
+  addgroup --system jwhois || echo "Failed to create jwhois group, cache functionality may be impaired."
 fi
 
 # Setgid binary to the jwhois group if no statoverride was set
 
-jwhoisoverride=`dpkg-statoverride --list /usr/bin/jwhois`
-if test "$jwhoisoverride" = ""; then
+jwhoisoverride=1
+dpkg-statoverride --list /usr/bin/jwhois > /dev/null || jwhoisoverride=0
+
+if test "$jwhoisoverride" = "0"; then
   if getent group jwhois > /dev/null; then
     if chown root.jwhois /usr/bin/jwhois; then
       chmod 02755 /usr/bin/jwhois || echo "Failed setting jwhois permissions, cache functionality may be impaired."
@@ -44,8 +45,10 @@ fi
 
 # Setgid cache directory to the jwhois group unless it's overriden
 
-cacheoverride=`dpkg-statoverride --list /var/cache/jwhois`
-if test "$cacheoverride" = ""; then
+cacheoverride=1
+dpkg-statoverride --list /var/cache/jwhois > /dev/null || cacheoverride=0
+
+if test "$cacheoverride" = "0"; then
   if getent group jwhois > /dev/null; then
     if chown root.jwhois /var/cache/jwhois; then
       chmod 0775 /var/cache/jwhois || echo "Failed setting cache directory permissions, cache functionality may be impaired."
