Added back getent test

diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -28,7 +28,9 @@ case "$1" in
     if test "$cacheoverride" = "1"; then
       dpkg-statoverride --remove /var/cache/jwhois || echo "Failed removing statoverride for /var/cache/jwhois"
     fi
-    groupdel jwhois || echo "Failed removing group \`jwhois'"
+    if getent group jwhois > /dev/null; then
+      groupdel jwhois || echo "Failed removing group \`jwhois'"
+    fi
     ;;
   upgrade)
     if dpkg --compare-versions "$2" ge 2.4.2-1; then
