2.4.2-5 changes

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -21,7 +21,7 @@ fi
 
 groupexist=1
 getent group jwhois > /dev/null || groupexist=0
-if test "$groupexist" = "0" then
+if test "$groupexist" = "0"; then
   # Group did not exist
   addgroup --system jwhois || echo "Failed to create jwhois group, cache functionality may be impaired."
 fi
@@ -62,10 +62,12 @@ if test "$cacheoverride" = "0"; then
 
     if test -e /var/cache/jwhois/jwhois.db; then
       chown root.jwhois /var/cache/jwhois/jwhois.db || echo "Failed setting cache file ownership, cache functionality may be impaired."
+      chmod 0660 /var/cache/jwhois/jwhois.db || echo "Failed setting cache permissions, cache functionality may be impaired."
     else
       if touch /var/cache/jwhois/jwhois.db; then
         if test -f /var/cache/jwhois/jwhois.db; then
           chown root.jwhois /var/cache/jwhois/jwhois.db || echo "Failed setting cache file ownership, cache functionality may be impaired."
+          chmod 0660 /var/cache/jwhois/jwhois.db || echo "Failed setting cache permissions, cache functionality may be impaired."
         else
           echo "Cache file is not a regular file, cache functionality may be impaired."
         fi
diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -18,11 +18,17 @@ case "$1" in
     # 2.4.2-1 -- 2.4.2-3, which adds a statoverride with the jwhois
     # group. Dpkg does not like to have a leftover statoverride with
     # a non-existing group.
-    dpkg-statoverride --remove /usr/bin/jwhois || echo "Failed removing statoverride for /usr/bin/jwhois"
-    dpkg-statoverride --remove /var/cache/jwhois || echo "Failed removing statoverride for /var/cache/jwhois"
-    if getent group jwhois > /dev/null; then
-      groupdel jwhois || echo "Failed removing group \`jwhois'"
+    jwhoisoverride=1
+    dpkg-statoverride --list /usr/bin/jwhois > /dev/null || jwhoisoverride=0
+    if test "$jwhoisoverride" = "1"; then
+      dpkg-statoverride --remove /usr/bin/jwhois || echo "Failed removing statoverride for /usr/bin/jwhois"
     fi
+    cacheoverride=1
+    dpkg-statoverride --list /var/cache/jwhois > /dev/null || cacheoverride=0
+    if test "$cacheoverride" = "1"; then
+      dpkg-statoverride --remove /var/cache/jwhois || echo "Failed removing statoverride for /var/cache/jwhois"
+    fi
+    groupdel jwhois || echo "Failed removing group \`jwhois'"
     ;;
   upgrade)
     if dpkg --compare-versions "$2" ge 2.4.2-1; then
