Use getent to check that jwhois group exists before trying to use it.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -19,16 +19,26 @@ fi
 
 # Add the group 'jwhois' that the cache uses
 
-addgroup --system jwhois || true
+if getent group jwhois > /dev/null; then
+  # Group already exists
+  true
+else
+  # Group did not exist
+  addgroup --system jwhois || true
+fi
 
 # Setgid binary to the jwhois group if no statoverride was set
 
 jwhoisoverride=`dpkg-statoverride --list /usr/bin/jwhois`
 if test "$jwhoisoverride" = ""; then
-  if chown root.jwhois /usr/bin/jwhois; then
-    chmod 02755 /usr/bin/jwhois || echo "Failed setting jwhois permissions, cache functionality may be impaired."
+  if getent group jwhois > /dev/null; then
+    if chown root.jwhois /usr/bin/jwhois; then
+      chmod 02755 /usr/bin/jwhois || echo "Failed setting jwhois permissions, cache functionality may be impaired."
+    else
+      echo "Failed setting jwhois ownership, cache functionality may be impaired."
+    fi
   else
-    echo "Failed setting jwhois ownership, cache functionality may be impaired."
+    echo "Jwhois group is missing, cache functionality will be impaired."
   fi
 fi
 
@@ -37,15 +47,19 @@ fi
 
 cacheoverride=`dpkg-statoverride --list /var/cache/jwhois`
 if test "$cacheoverride" = ""; then
-  if chown root.jwhois /var/cache/jwhois; then
-    chmod 0775 /var/cache/jwhois || echo "Failed setting cache directory permissions, cache functionality may be impaired."
+  if getent group jwhois > /dev/null; then
+    if chown root.jwhois /var/cache/jwhois; then
+      chmod 0775 /var/cache/jwhois || echo "Failed setting cache directory permissions, cache functionality may be impaired."
+    else
+      echo "Failed setting cache directory ownership, cache functionality may be impaired."
+    fi
+
+    # Make sure the cache, if it exists, has the correct group ownership
+
+    if test -e /var/cache/jwhois/jwhois.db; then
+      chgrp jwhois /var/cache/jwhois/jwhois.db || echo "Failed setting cache file ownership, cache functionality may be impaired."
+    fi
   else
-    echo "Failed setting cache directory ownership, cache functionality may be impaired."
-  fi
-
-  # Make sure the cache, if it exists, has the correct group ownership
-
-  if test -e /var/cache/jwhois/jwhois.db; then
-    chgrp jwhois /var/cache/jwhois/jwhois.db || echo "Failed setting cache file ownership, cache functionality may be impaired."
+    echo " Jwhois group is missing, not setting ownership of cache directory."
   fi
 fi
diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -20,7 +20,9 @@ case "$1" in
     # a non-existing group.
     dpkg-statoverride --remove /usr/bin/jwhois || echo "Failed removing statoverride for /usr/bin/jwhois"
     dpkg-statoverride --remove /var/cache/jwhois || echo "Failed removing statoverride for /var/cache/jwhois"
-    groupdel jwhois || echo "Failed removing group \`jwhois'"
+    if getent group jwhois > /dev/null; then
+      groupdel jwhois || echo "Failed removing group \`jwhois'"
+    fi
     ;;
   upgrade)
     if dpkg --compare-versions "$2" ge 2.4.2-1; then
